#!/bin/bash
# Usage: ./0-iamsomeoneelse username

# Make sure the script is being run as root
if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root"
    exit 1
fi

# Check if a username was provided as an argument
if [ $# -ne 1 ]; then
    echo "Usage: $0 username"
    exit 1
fi

# Run whoami command as the specified user
su - "$1" -c 'whoami'